M_NAME ?= epiphany
M_VPC_ID ?= unset
M_SUBNET_IDS ?= null
M_REGION ?= eu-central-1
M_PRIVATE_ROUTE_TABLE_ID ?= unset
M_DISK_SIZE ?= 36
M_AUTOSCALER_SCALE_DOWN_UTILIZATION_THRESHOLD ?= 0.65
M_EC2_SSH_KEY ?= null
M_AMI_TYPE ?= AL2_x86_64
M_WORKER_GROUPS_NAME ?= default_wg
M_WORKER_GROUPS_INSTANCE_TYPE ?= t2.small
M_WORKER_GROUPS_ADG_DESIRED_CAPACITY ?= 1
M_WORKER_GROUPS_ASG_MIN_SIZE ?= 1
M_WORKER_GROUPS_ASG_MAX_SIZE ?= 1

# aws credentials
M_AWS_ACCESS_KEY ?= unset
M_AWS_SECRET_KEY ?= unset
